---
abstract: 'Collection of modules for ExtJS'
author:
  - 'Moritz Onken <onken@netcubed.de>'
build_requires:
  Catalyst: 0
  Catalyst::Engine::HTTP: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Request::REST::ForBrowsers: 0
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  DBIx::Class: 0
  DBIx::Class::ResultSet: 0
  DBIx::Class::Schema: 0
  English: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  Getopt::Long: 0
  HTTP::Request::Common: 0
  JSON: 0
  Module::Build: 0.3601
  Path::Class::File: 0
  Pod::Usage: 0
  Test::More: 0.94
  Test::WWW::Mechanize::Catalyst: 0
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102221, CPAN::Meta::Converter version 2.101610'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-ExtJS
no_index:
  directory:
    - example
    - tutorial
provides:
  CatalystX::Action::ExtJS::Deserialize:
    file: lib/CatalystX/Action/ExtJS/Deserialize.pm
    version: 1.110000
  CatalystX::Action::ExtJS::Direct:
    file: lib/CatalystX/Action/ExtJS/Direct.pm
    version: 1.110000
  CatalystX::Action::ExtJS::REST:
    file: lib/CatalystX/Action/ExtJS/REST.pm
    version: 1.110000
  CatalystX::Action::ExtJS::Serialize:
    file: lib/CatalystX/Action/ExtJS/Serialize.pm
    version: 1.110000
  CatalystX::Controller::ExtJS::Direct:
    file: lib/CatalystX/Controller/ExtJS/Direct.pm
    version: 1.110000
  CatalystX::Controller::ExtJS::Direct::API:
    file: lib/CatalystX/Controller/ExtJS/Direct/API.pm
    version: 1.110000
  CatalystX::Controller::ExtJS::Direct::Route:
    file: lib/CatalystX/Controller/ExtJS/Direct/Route.pm
    version: 1.110000
  CatalystX::Controller::ExtJS::Direct::Route::Chained:
    file: lib/CatalystX/Controller/ExtJS/Direct/Route.pm
    version: 1.110000
  CatalystX::Controller::ExtJS::Direct::Route::Factory:
    file: lib/CatalystX/Controller/ExtJS/Direct/Route.pm
    version: 1.110000
  CatalystX::Controller::ExtJS::Direct::Route::REST:
    file: lib/CatalystX/Controller/ExtJS/Direct/Route.pm
    version: 1.110000
  CatalystX::Controller::ExtJS::Direct::Route::REST::ExtJS:
    file: lib/CatalystX/Controller/ExtJS/Direct/Route.pm
    version: 1.110000
  CatalystX::Controller::ExtJS::ImageChooser:
    file: lib/CatalystX/Controller/ExtJS/ImageChooser.pm
    version: 1.110000
  CatalystX::Controller::ExtJS::REST:
    file: lib/CatalystX/Controller/ExtJS/REST.pm
    version: 1.110000
  CatalystX::ExtJS:
    file: lib/CatalystX/ExtJS.pm
    version: 1.110000
  CatalystX::ExtJS::Tutorial:
    file: lib/CatalystX/ExtJS/Tutorial.pm
    version: 1.110000
  CatalystX::ExtJS::Tutorial::Direct:
    file: lib/CatalystX/ExtJS/Tutorial/Direct.pm
    version: 1.110000
  CatalystX::TraitFor::Request::ExtJS:
    file: lib/CatalystX/TraitFor/Request/ExtJS.pm
    version: 1.110000
requires:
  Carp: 0
  Catalyst::Action: 0
  Catalyst::Action::Deserialize: 0
  Catalyst::Action::REST: 0.83
  Catalyst::Action::RenderView: 0
  Catalyst::Action::Serialize: 0
  Catalyst::Controller: 0
  Catalyst::Controller::REST: 0
  Catalyst::Runtime: 5.80024
  Catalyst::Utils: 0
  Class::Accessor::Fast: 0
  Config::Any: 0
  DBIx::Class: 0.08121
  HTML::Entities: 0
  HTML::FormFu::ExtJS: 0.076
  HTML::FormFu::Model::DBIC: 0.06
  JSON::Any: 0
  JSON::XS: 0
  Lingua::EN::Inflect: 0
  List::Util: 0
  Moose: 1.06
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::MethodAttributes: 0
  Path::Class: 0
  Scalar::Util: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CatalystX-ExtJS
  homepage: http://search.cpan.org/dist/CatalystX-ExtJS/
  repository: http://github.com/monken/catalystx-extjs
version: 1.110000
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@Filter/CompileTests'
      version: 1.101600
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@Filter/CriticTests'
      version: 1.100140
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Filter/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@Filter/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Filter/MetaTests'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@Filter/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@Filter/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@Filter/ReportVersions'
      version: 1.101600
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@Filter/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@Filter/AutoPrereq'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.100710
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Filter/Prepender'
      version: 1.101590
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Filter/Bugtracker'
      version: 1.101490
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Filter/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Filter/Repository'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/MetaProvides::Package'
      version: 1.10027802
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Filter/ModuleBuild'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Filter/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/Git/Check'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/Git/Commit'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/Git/Tag'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/Git/Push'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereq
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 1.101550
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102221
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102221
